import Head from 'next/head';
import Image from 'next/image';
import Script from 'next/script';


import styles from '../styles/Home.module.css';



//images
import pic1 from "../public/posters/IMG_20220711_230134_426.jpg";
import pic2 from "../public/posters/IMG_20220711_230142_609.jpg";
import pic3 from "../public/posters/IMG_20220711_230151_369.jpg";
import pic4 from "../public/posters/IMG_20220711_230220_200.jpg";
import pic5 from "../public/posters/IMG_20220711_230227_261.jpg";
import pic6 from "../public/posters/IMG_20220722_232450_162.jpg";




// bootStrap.
// style.
// fullSite.







export default function Home(){
  

  return (
    <>

      <Head>
        <title>purpleAnime</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" strategy="lazyload"></Script> */}
      <Script src="https://kit.fontawesome.com/f3d9799b4a.js" crossorigin="anonymous"></Script>
      <Script src="js/bootstrap.js"></Script>

      <Script>
        
      </Script>

      <main className={styles.main}>
        <nav className="navbar navbar-dark fixed-top" style={{color: '#ff00fa', backgroundColor: '#00000015', width: '100vw'}}>
          <div className="container-fluid" style={{color: '#ff00fa', backgroundColor: '#00000000'}}>
            <a style={{color: '#ff00fa'}} className="navbar-brand shitty-nme" href="#">purpleAnime</a>
            <div className="navbar-toggler" style={{color: '#ff00fa', border: 0}} type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar">
              <i className="fa-solid fa-list-ul" />
            </div>
            <div style={{color: '#ff00fa'}} className="offcanvas offcanvas-end text-bg-dark" tabIndex={-1} id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel">
              <div style={{color: '#ff00fa', backgroundColor: "#000"}} className="offcanvas-header">
                <h5 style={{color: '#ff00fa'}} className="offcanvas-title" id="offcanvasDarkNavbarLabel">purpleAnime</h5>
                <button style={{color: '#ff00fa'}} type="button" className="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close" />
              </div>
              <div style={{color: '#ff00fa', backgroundColor: "#000"}} className="offcanvas-body">
                <ul style={{color: '#ff00fa'}} className="navbar-nav justify-content-end flex-grow-1 pe-3">
                  <li style={{color: '#ff00fa'}} className="nav-item">
                    <a style={{color: '#ff00fa'}} className="nav-link active" aria-current="page" href="index.html">Home</a>
                  </li>
                  <li style={{color: '#ff00fa'}} className="nav-item">
                    <a style={{color: '#ff00fa'}} className="nav-link" href="https://www.youtube.com/channel/UCuMHHOSI5niZo-_aWZQRA7Q">YouThoob</a>
                  </li>
                  <li style={{color: '#ff00fa'}} className="nav-item dropdown">
                    <a style={{color: '#ff00fa'}} className="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Follow us
                    </a>
                    <ul style={{backgroundColor: '#ff00fa', borderRadius: 'none', color: '#ff00fa'}} className="dropdown-menu dropdown-menu-dark">
                      <li style={{color: '#ff00fa'}}><a className="dropdown-item" href="https://instagram.com/kakashi_69_bvf?igshid=YmMyMTA2M2Y="><i className="fa-brands fa-instagram" />&nbsp;Instagram</a></li>
                      <li style={{color: '#ff00fa'}}><a className="dropdown-item" href="https://instagram.com/kakashi.java?igshid=YmMyMTA2M2Y="><i className="fa-brands fa-instagram" />&nbsp;Instagram</a></li>
                      <li style={{color: '#ff00fa'}}>
                        <hr style={{color: '#ff00fa'}} className="dropdown-divider" />
                      </li>
                      <li style={{color: '#ff00fa'}}><a className="dropdown-item" href="https://www.instagram.com/direct/t/340282366841710300949128295980138641074">Contact us</a></li>
                    </ul>
                  </li>
                </ul>
                <form style={{color: '#ff00fa'}} className="d-flex" role="search">
                  <input id="srcInp" list="input" className="from-controle-me2" type="search" placeholder="Search" aria-label="Search" />
                  <datalist id="input">
                    <option value="Naruto" />
                    <option value="Naruto Shippuden" />
                    <option value="Death Note" />
                    <option value="Fruits Basket" />
                    <option value="Darling in the Franxx" />
                    <option value="Boruto" />
                    <option value="Demon Slayer" />
                    <option value="Rent a Girlfriend" />
                  </datalist>
                  <div style={{color: '#ff00fa'}} className="src-box"><i className="fa-solid fa-magnifying-glass" style={{color: '#ff00fa'}} /></div>
                </form>
              </div>
            </div>
          </div>
        </nav>

        <div id="carouselExampleControls" className="carousel slide" data-bs-ride="carousel" style={{maxWidth: '100vw', marginTop: '10vw'}}>
          <div className="carousel-inner">
            <div className="carousel-item active">
              <Image src={pic1} className="d-block w-100" alt="" style={{pointerEvents: 'none', aspectRatio: "16/9 !important"}} />
            </div>
            <div className="carousel-item">
              <Image src={pic2} className="d-block w-100" alt="" style={{pointerEvents: 'none', aspectRatio: "16/9 !important"}} />
            </div>
            <div className="carousel-item">
              <Image src={pic3} className="d-block w-100" alt="" style={{pointerEvents: 'none', aspectRatio: "16/9 !important"}} />
            </div>
            <div className="carousel-item">
              <Image src={pic4} className="d-block w-100" alt="" style={{pointerEvents: 'none', aspectRatio: "16/9 !important"}} />
            </div>
            <div className="carousel-item">
              <Image src={pic5} className="d-block w-100" alt="" style={{pointerEvents: 'none', aspectRatio: "16/9 !important"}} />
            </div>
            <div className="carousel-item">
              <Image src={pic6} className="d-block w-100" alt="" style={{pointerEvents: 'none', aspectRatio: "16/9 !important"}} />
            </div>
          </div>
          <button className="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
            <span className="carousel-control-prev-icon" aria-hidden="true" />
            <span className="visually-hidden">Previous</span>
          </button>
          <button className="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
            <span className="carousel-control-next-icon" aria-hidden="true" />
            <span className="visually-hidden">Next</span>
          </button>
        </div>


  
        <a href="fullSite.html" style={{textDecoration: 'none'}}>
          <div className="view_full_site_box">
            <center>
              View Full Site
            </center>
          </div>
        </a>
        <center id="srcCenter">
          <div style={{color: '#ff00fa'}} id="lodingOfSrc" className="spinner-border" role="status">
            <span className="visually-hidden">
              shit
            </span>
          </div>
          <div id="srcBody" />
        </center>
      </main>


      {/*content*/}
      <hr className="hr_1" />
      <div>
        <a href="Movie69bvf.html">
        </a><a href="Movie69bvf.html">
        </a><a href="Movie69bvf.html">
        </a><a href="Movie69bvf.html">
        </a><table>
          {/*Movie*/}
          <tbody>
            <tr className="carmdz">
              <td>
                <h className="content-----txt">Movie</h>
              </td>
            </tr>
            {/*Top Airing*/}
            <tr className="carmdz">
              <td>
                <h className="content-----txt">Airing</h>
              </td>
            </tr>
            {/*Populer*/}
            <tr className="carmdz">
              <td>
                <h className="content-----txt">Populer</h>
              </td>
            </tr>
            {/*Anime List*/}
            <tr className="carmdz">
              <td>
                <h className="content-----txt">Anime List</h>
              </td>
            </tr>
            {/*/*/}
          </tbody></table>
      </div><hr className="hr" />
      {/*/content*/}
      <footer className="text-center text-white" style={{backgroundColor: '#000000', marginBottom: 5}}>
        {/*Ads*/}
        {/*/Ads*/}
        {/* Grid container */}
        <div className="container pt-4" style={{color: '#ff00fa'}}>
          {/* Section: Social media */}
          <section className="mb-4">
            {/* Youthoob */}
            <a className="shittySMLink" href="#!" role="button" data-mdb-ripple-color="dark"><i className="fa-brands fa-youtube" style={{color: '#ff00fa'}} /></a>
            {/* Google */}
            <a className="shittySMLink" href="#!" role="button" data-mdb-ripple-color="dark">
              <i className="fab fa-google" />
            </a>
            {/* Instagram */}
            <a className="shittySMLink" href="https://instagram.com/kakashi_69_bvf?igshid=YmMyMTA2M2Y=" role="button" data-mdb-ripple-color="dark"><i className="fab fa-instagram" /></a>
            {/* Linkedin */}
            <a className="shittySMLink" href="#!" role="button" data-mdb-ripple-color="dark"><i className="fab fa-linkedin" /></a>
            {/* Github */}
            <a className="shittySMLink" href="#!" role="button" data-mdb-ripple-color="dark"><i className="fab fa-github" /></a>
          </section>
          {/* Section: Social media */}
        </div>
        {/* Grid container */}
      </footer>
      {/*/footer*/}


      

    </>
  );
}













// export default function Home() {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <nav className={` ${fullSite.navbar} ${bootStrap.navbar-dark} ${bootStrap.fixed-top}`} style={{color: '#ff00fa', backgroundColor: '#00000015', width: '100vw'}}>
//           <div className={` ${bootStrap.container-fluid}`} style={{color: '#ff00fa', backgroundColor: '#00000000'}}>
//             <a style={{color: '#ff00fa'}} className={`${bootStrap.navbar-brand}  ${style.shitty-nme}`} href="#">purpleAnime</a>
//             <div className={bootStrap.navbar-toggler} style={{color: '#ff00fa', border: 0}} type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar">
//               <i className="fa-solid fa-list-ul" />
//             </div>
//             <div style={{color: '#ff00fa'}} className={` ${bootStrap.offcanvas}  ${bootStrap.offcanvas-end}  ${bootStrap.text-bg-dark}`} tabIndex={-1} id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel">
//               <div style={{color: '#ff00fa'}} className={bootStrap.offcanvas-header}>
//                 <h5 style={{color: '#ff00fa'}} className={bootStrap.offcanvas-title} id="offcanvasDarkNavbarLabel">purpleAnime</h5>
//                 <button style={{color: '#ff00fa'}} type="button" className={` ${bootStrap.btn-close}  ${bootStrap.btn-close-white}`} data-bs-dismiss="offcanvas" aria-label="Close" />
//               </div>
//               <div style={{color: '#ff00fa'}} className={bootStrap.offcanvas-body}>
//                 <ul style={{color: '#ff00fa'}} className={` ${bootStrap.navbar-nav}  ${bootStrap.justify-content-end}  ${bootStrap.flex-grow-1}  ${bootStrap.pe-3}`}>
//                   <li style={{color: '#ff00fa'}} className={bootStrap.nav-item}>
//                     <a style={{color: '#ff00fa'}} className={bootStrap.nav-link+" "+active} aria-current="page" href="index.html">Home</a>
//                   </li>
//                   <li style={{color: '#ff00fa'}} className={bootStrap.nav-item}>
//                     <a style={{color: '#ff00fa'}} className={bootStrap.nav-link} href="https://www.youtube.com/channel/UCuMHHOSI5niZo-_aWZQRA7Q">YouThoob</a>
//                   </li>
//                   <li style={{color: '#ff00fa'}} className={` ${bootStrap.nav-item}  ${bootStrap.dropdown}`}>
//                     <a style={{color: '#ff00fa'}} className={` ${bootStrap.nav-link}  ${bootStrap.dropdown-toggle}`} href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
//                       Follow us
//                     </a>
//                     <ul style={{backgroundColor: '#ff00fa', borderRadius: 'none', color: '#ff00fa'}} className={` ${bootStrap.dropdown-menu}  ${bootStrap.dropdown-menu-dark}`}>
//                       <li style={{color: '#ff00fa'}}><a className={bootStrap.dropdown-item} href="https://instagram.com/kakashi_69_bvf?igshid=YmMyMTA2M2Y="><i className="fa-brands fa-instagram" />&nbsp;Instagram</a></li>
//                       <li style={{color: '#ff00fa'}}><a className={bootStrap.dropdown-item} href="https://instagram.com/kakashi.java?igshid=YmMyMTA2M2Y="><i className="fa-brands fa-instagram" />&nbsp;Instagram</a></li>
//                       <li style={{color: '#ff00fa'}}>
//                         <hr style={{color: '#ff00fa'}} className={bootStrap.dropdown-divider} />
//                       </li>
//                       <li style={{color: '#ff00fa'}}><a className={bootStrap.dropdown-item} href="https://www.instagram.com/direct/t/340282366841710300949128295980138641074">Contact us</a></li>
//                     </ul>
//                   </li>
//                 </ul>
//                 <span style={{color: '#ff00fa'}} className="d-flex" role="search">
//                   <input id="srcInp" onchange="search()" list="input" className={style.from-controle-me2} type="search" placeholder="Search" aria-label="Search" />
//                   <datalist id="input">
//                     <option value="Naruto" />
//                     <option value="Naruto Shippuden" />
//                     <option value="Death Note" />
//                     <option value="Fruits Basket" />
//                     <option value="Darling in the Franxx" />
//                     <option value="Boruto" />
//                     <option value="Demon Slayer" />
//                     <option value="Rent a Girlfriend" />
//                   </datalist>
//                   <div style={{color: '#ff00fa'}} className="src-box"><i className="fa-solid fa-magnifying-glass" style={{color: '#ff00fa'}} /></div>
//                 </span></div>
//             </div>
//           </div>
//         </nav>

//       </main>





//       <footer className={styles.footer}>
        
//       </footer>
//     </div>
//   )
// }















// export default function Home(){
  

//   return (
//     <>

//       <Head>
//         <title>purpleAnime</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//         <script src="js/srcEng.js"></script>
//       </Head>
//       {/* <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" strategy="lazyload"></Script> */}
//       <Script src="https://kit.fontawesome.com/f3d9799b4a.js" crossorigin="anonymous"></Script>
//       <Script src="js/bootstrap.js"></Script>
      
      
//       <main className={styles.main}>
//         <nav className="navbar navbar-dark fixed-top" style={{color: '#ff00fa', backgroundColor: '#00000015', width: '100vw'}}>
//           <div className="container-fluid" style={{color: '#ff00fa', backgroundColor: '#00000000'}}>
//             <a style={{color: '#ff00fa'}} className="navbar-brand shitty-nme" href="#">purpleAnime</a>
//             <div className="navbar-toggler" style={{color: '#ff00fa', border: 0}} type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar">
//               <i className="fa-solid fa-list-ul" />
//             </div>
//             <div style={{color: '#ff00fa'}} className="offcanvas offcanvas-end text-bg-dark" tabIndex={-1} id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel">
//               <div style={{color: '#ff00fa', backgroundColor: "#000"}} className="offcanvas-header">
//                 <h5 style={{color: '#ff00fa'}} className="offcanvas-title" id="offcanvasDarkNavbarLabel">purpleAnime</h5>
//                 <button style={{color: '#ff00fa'}} type="button" className="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close" />
//               </div>
//               <div style={{color: '#ff00fa', backgroundColor: "#000"}} className="offcanvas-body">
//                 <ul style={{color: '#ff00fa'}} className="navbar-nav justify-content-end flex-grow-1 pe-3">
//                   <li style={{color: '#ff00fa'}} className="nav-item">
//                     <a style={{color: '#ff00fa'}} className="nav-link active" aria-current="page" href="index.html">Home</a>
//                   </li>
//                   <li style={{color: '#ff00fa'}} className="nav-item">
//                     <a style={{color: '#ff00fa'}} className="nav-link" href="https://www.youtube.com/channel/UCuMHHOSI5niZo-_aWZQRA7Q">YouThoob</a>
//                   </li>
//                   <li style={{color: '#ff00fa'}} className="nav-item dropdown">
//                     <a style={{color: '#ff00fa'}} className="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
//                       Follow us
//                     </a>
//                     <ul style={{backgroundColor: '#ff00fa', borderRadius: 'none', color: '#ff00fa'}} className="dropdown-menu dropdown-menu-dark">
//                       <li style={{color: '#ff00fa'}}><a className="dropdown-item" href="https://instagram.com/kakashi_69_bvf?igshid=YmMyMTA2M2Y="><i className="fa-brands fa-instagram" />&nbsp;Instagram</a></li>
//                       <li style={{color: '#ff00fa'}}><a className="dropdown-item" href="https://instagram.com/kakashi.java?igshid=YmMyMTA2M2Y="><i className="fa-brands fa-instagram" />&nbsp;Instagram</a></li>
//                       <li style={{color: '#ff00fa'}}>
//                         <hr style={{color: '#ff00fa'}} className="dropdown-divider" />
//                       </li>
//                       <li style={{color: '#ff00fa'}}><a className="dropdown-item" href="https://www.instagram.com/direct/t/340282366841710300949128295980138641074">Contact us</a></li>
//                     </ul>
//                   </li>
//                 </ul>
//                 <form style={{color: '#ff00fa'}} className="d-flex" role="search">
//                   <input onchange="search()" id="srcInp" list="input" className="from-controle-me2" type="search" placeholder="Search" aria-label="Search" />
//                   <datalist id="input">
//                     <option value="Naruto" />
//                     <option value="Naruto Shippuden" />
//                     <option value="Death Note" />
//                     <option value="Fruits Basket" />
//                     <option value="Darling in the Franxx" />
//                     <option value="Boruto" />
//                     <option value="Demon Slayer" />
//                     <option value="Rent a Girlfriend" />
//                   </datalist>
//                   <div style={{color: '#ff00fa'}} className="src-box"><i className="fa-solid fa-magnifying-glass" style={{color: '#ff00fa'}} /></div>
//                 </form>
//               </div>
//             </div>
//           </div>
//         </nav>
//         <Script src="js/srcEng.js" strategy="afterInteractive"></Script>

//         <div id="carouselExampleControls" className="carousel slide" data-bs-ride="carousel" style={{maxWidth: '100vw', marginTop: '10vw'}}>
//           <div className="carousel-inner">
//             <div className="carousel-item active">
//               <Image src={pic1} className="d-block w-100" alt="" style={{pointerEvents: 'none', aspectRatio: "16/9 !important"}} />
//             </div>
//             <div className="carousel-item">
//               <Image src={pic2} className="d-block w-100" alt="" style={{pointerEvents: 'none', aspectRatio: "16/9 !important"}} />
//             </div>
//             <div className="carousel-item">
//               <Image src={pic3} className="d-block w-100" alt="" style={{pointerEvents: 'none', aspectRatio: "16/9 !important"}} />
//             </div>
//             <div className="carousel-item">
//               <Image src={pic4} className="d-block w-100" alt="" style={{pointerEvents: 'none', aspectRatio: "16/9 !important"}} />
//             </div>
//             <div className="carousel-item">
//               <Image src={pic5} className="d-block w-100" alt="" style={{pointerEvents: 'none', aspectRatio: "16/9 !important"}} />
//             </div>
//             <div className="carousel-item">
//               <Image src={pic6} className="d-block w-100" alt="" style={{pointerEvents: 'none', aspectRatio: "16/9 !important"}} />
//             </div>
//           </div>
//           <button className="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
//             <span className="carousel-control-prev-icon" aria-hidden="true" />
//             <span className="visually-hidden">Previous</span>
//           </button>
//           <button className="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
//             <span className="carousel-control-next-icon" aria-hidden="true" />
//             <span className="visually-hidden">Next</span>
//           </button>
//         </div>


  
//         <a href="fullSite.html" style={{textDecoration: 'none'}}>
//           <div className="view_full_site_box">
//             <center>
//               View Full Site
//             </center>
//           </div>
//         </a>
//         <center id="srcCenter">
//           <div style={{color: '#ff00fa'}} id="lodingOfSrc" className="spinner-border" role="status">
//             <span className="visually-hidden">
//               shit
//             </span>
//           </div>
//           <div id="srcBody" />
//         </center>
//       </main>


//       {/*content*/}
//       <hr className="hr_1" />
//       <div>
//         <a href="Movie69bvf.html">
//         </a><a href="Movie69bvf.html">
//         </a><a href="Movie69bvf.html">
//         </a><a href="Movie69bvf.html">
//         </a><table>
//           {/*Movie*/}
//           <tbody><tr className="carmdz">
//               <td>
//                 <h className="content-----txt">Movie</h>
//               </td>
//             </tr>
//             {/*Top Airing*/}
//             <tr className="carmdz">
//               <td>
//                 <h className="content-----txt">Airing</h>
//               </td>
//             </tr>
//             {/*Populer*/}
//             <tr className="carmdz">
//               <td>
//                 <h className="content-----txt">Populer</h>
//               </td>
//             </tr>
//             {/*Anime List*/}
//             <tr className="carmdz">
//               <td>
//                 <h className="content-----txt">Anime List</h>
//               </td>
//             </tr>
//             {/*/*/}
//           </tbody></table>
//       </div><hr className="hr" />
//       {/*/content*/}
//       <footer className="text-center text-white" style={{backgroundColor: '#000000', marginBottom: 5}}>
//         {/*Ads*/}
//         {/*/Ads*/}
//         {/* Grid container */}
//         <div className="container pt-4" style={{color: '#ff00fa'}}>
//           {/* Section: Social media */}
//           <section className="mb-4">
//             {/* Youthoob */}
//             <a className="shittySMLink" href="#!" role="button" data-mdb-ripple-color="dark"><i className="fa-brands fa-youtube" style={{color: '#ff00fa'}} /></a>
//             {/* Google */}
//             <a className="shittySMLink" href="#!" role="button" data-mdb-ripple-color="dark">
//               <i className="fab fa-google" />
//             </a>
//             {/* Instagram */}
//             <a className="shittySMLink" href="https://instagram.com/kakashi_69_bvf?igshid=YmMyMTA2M2Y=" role="button" data-mdb-ripple-color="dark"><i className="fab fa-instagram" /></a>
//             {/* Linkedin */}
//             <a className="shittySMLink" href="#!" role="button" data-mdb-ripple-color="dark"><i className="fab fa-linkedin" /></a>
//             {/* Github */}
//             <a className="shittySMLink" href="#!" role="button" data-mdb-ripple-color="dark"><i className="fab fa-github" /></a>
//           </section>
//           {/* Section: Social media */}
//         </div>
//         {/* Grid container */}
//       </footer>
//       {/*/footer*/}


      

//     </>
//   );
// }

